Name:           ros-kinetic-bag-tools
Version:        0.0.3
Release:        0%{?dist}
Summary:        ROS bag_tools package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/bag_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       console-bridge-devel
Requires:       ros-kinetic-camera-calibration-parsers
Requires:       ros-kinetic-cv-bridge
Requires:       ros-kinetic-image-geometry
Requires:       ros-kinetic-image-proc
Requires:       ros-kinetic-message-filters
Requires:       ros-kinetic-rosbag
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-stereo-image-proc
BuildRequires:  console-bridge-devel
BuildRequires:  ros-kinetic-camera-calibration-parsers
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cv-bridge
BuildRequires:  ros-kinetic-image-geometry
BuildRequires:  ros-kinetic-image-proc
BuildRequires:  ros-kinetic-message-filters
BuildRequires:  ros-kinetic-rosbag
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-stereo-image-proc

%description
ROS tools and scripts related to bagfiles

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Feb 24 2017 Miquel Massot <miquel.massot@uib.es> - 0.0.3-0
- Autogenerated by Bloom

* Thu Feb 23 2017 Miquel Massot <miquel.massot@uib.es> - 0.0.2-0
- Autogenerated by Bloom

